Fern/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.static import serve

urlpatterns = [
    path("admin/doc/", include("django.contrib.admindocs.urls")),
    path("admin/", admin.site.urls),
    path("", include("apps.core.urls")),
    path("polls/", include("apps.polls.urls")),
    path("forum/", include("apps.forum.urls")),
    path("accounts/", include("apps.account.urls")),
    path("accounts/", include("apps.account.admin_urls")),
    path("notifications/", include("apps.notification.urls")),
    path("", include("user_sessions.urls", "user_sessions")),
    path("media/<path:path>", serve, {"document_root": settings.MEDIA_ROOT}),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/account/urls.py
from django.urls import path, include
from . import views

app_name = "account"
urlpatterns = [
    path("", include("django.contrib.auth.urls")),
    path("register/", views.signup, name="signup"),
    path("user/<str:username>/", views.user_detail, name="user_detail"),
    path("user/<str:username>/preference/", views.user_preference, name="user_preference"),
]

apps/core/urls.py
from django.urls import path
from . import views

app_name = "core"
urlpatterns = [
    path("", views.FrontpageView.as_view(), name="frontpage"),
    path("home/", views.HomeView.as_view(), name="homepage"),
    path(
        "convert/md/", views.convert_markdown_to_html, name="convert_markdown_to_html"
    ),
    path("search/", views.search, name="search"),
]

apps/forum/urls.py
from django.urls import path
from . import views, islands

app_name = "forum"

urlpatterns = [
    path("create/", views.thread_create, name="thread_create"),
    path("create/<str:category_slug>/", views.thread_create, name="thread_create"),
    path("t/<slug:slug>/", views.thread_detail, name="thread_detail"),
    path("t/<slug:thread_slug>/<int:post_pk>", views.post_detail, name="post_detail"),
    # Post edit
    path("<int:pk>/edit/", views.post_edit, name="post_edit"),
    path("<int:pk>/reply/", views.reply_create, name="reply_create"),
    path("<int:pk>/delete/", views.delete_post, name="delete_post"),

    path('c/<str:slug>/', views.threads_by_category, name='threads_by_category'),
    path('c/', views.categories_list, name='categories_list'),

    # Islands
    path("islands/reply/<int:pk>/", islands.reply_form, name="reply_form"),
    path("islands/like/<int:pk>/", islands.like_post, name="like_post"),
    path('islands/threads/<int:pk>/', islands.thread_post_list, name='thread_post_list'),
    path('islands/threads/<int:pk>/reply-button/', islands.reply_button, name='reply_button'),
    path('islands/threads/<int:pk>/post-block/', islands.post_block, name='post_block'),
    path('islands/category-filter/', islands.category_filter, name='category_filter'),

    # Upload
    path("upload/", views.upload_file, name="upload_file"),  # New upload path
    path('islands/upload-modal/', islands.upload_modal, name='upload_modal'),
    path('islands/upload-form/', islands.upload_form, name='upload_form'),
    path('islands/existing-uploads/', islands.existing_uploads, name='existing_uploads_island'),
    path('islands/close-modal/', islands.close_modal, name='close_modal'),
    path('islands/insert-upload/<int:pk>/', islands.insert_upload, name='insert_upload'),

    path("uploads/", views.existing_uploads, name="existing_uploads"),  # New existing uploads path
    path("uploads/<int:pk>/delete/", views.delete_upload, name="delete_upload"),

    path('link/<int:pk>/click/', views.link_click, name='link_click')


]

apps/notification/urls.py
from django.urls import path
from . import views

app_name = "notification"
urlpatterns = [
    # Other URL patterns
    path("", views.notification_page, name="notification_page"),
    path("<int:pk>/redirect/", views.redirect_to_notification_target, name="redirect_to_notification_target"),
]

apps/core/models.py
from django.db import models
# Define you models here.

apps/core/views.py
from django.shortcuts import HttpResponse, render
from django.views import View
from django.views.generic import TemplateView
from django.db.models import Q

from apps.account.templatetags.user_mention import user_mention
from apps.forum.models import Category, Thread, Post
from apps.account.models import User

from .templatetags.convert_markdown import convert_markdown
from .utils import paginate, is_htmx


class FrontpageView(View):
    template_name = "core/frontpage.html"

    def get(self, request):
        categories = Category.objects.filter(parent__isnull=True).prefetch_related(
            "subcategories", "threads"
        )
        context = {"categories": categories}
        return render(request, self.template_name, context)


def convert_markdown_to_html(request):
    input_param = request.POST.get("name", default="text")
    text = request.POST.get(input_param)
    html = user_mention(convert_markdown(text))
    return HttpResponse(html)


class HomeView(TemplateView):
    template_name = "core/home.html"


def search(request):
    query = request.GET.get("q", "")
    type_filter = request.GET.get("type", "threads")
    results = []
    if query and type_filter:
        if type_filter == "threads":
            results = (
                Thread.objects.filter(
                    Q(title__icontains=query)
                    | Q(created_at__icontains=query)
                    | Q(creator__username__icontains=query)
                )
                .select_related("category")
                .prefetch_related("posts")
                .order_by("-created_at")
            )
        elif type_filter == "posts":
            results = (
                Post.objects.filter(
                    Q(thread__title__icontains=query) | Q(body__icontains=query)
                )
                .select_related("thread", "thread__category")
                .order_by("-created_at")
            )
        elif type_filter == "users":
            results = (
                User.objects.filter(username__icontains=query)
                .select_related("userprofile")
                .prefetch_related("posts")
                .order_by("-date_joined")
            )
        elif type_filter == "categories":
            results = (
                Category.objects.filter(name__icontains=query)
                .prefetch_related("threads")
                .order_by("name")
            )
    results = paginate(request, results, 10)
    context = {"query": query, "type_filter": type_filter, "results": results}
    if is_htmx(request):
        return render(request, "core/islands/search_results.html", context)
    else:
        return render(request, "core/search.html", context)

apps/core/templates/core/islands/frontpage_desktop_partial.html
{% load humanize %}
<div>
    <div class="box m-0"
        style="background-color: transparent; border-left: 0.5rem  solid; border-radius: 0%; box-shadow: none;">

        <div class="columns is-multiline">
            <div class="column is-4">
                <p class="subtitle is-4">
                    <a href="{% url 'forum:categories_list' %}">
                        Category
                    </a>
                </p>
            </div>
            <div class="column is-2">
                <p class="subtitle is-4">
                    Topics
                </p>
            </div>
            <div class="column">
                <p class="subtitle is-4">
                    Threads
                </p>
            </div>
        </div>
    </div>
    {% for category in categories %}
    <div class="box m-0"
        style="background-color: transparent; border-left: 0.5rem {{category.color}} solid; border-radius: 0%; box-shadow: none;">
        <div class="columns is-mutliline">
            <div class="column is-4">
                <h5 class="title is-5">
                    <a href="{% url 'forum:threads_by_category' category.slug %}">
                        {{ category.name }}
                    </a>
                </h5>
                <p class="subtitle is-6">
                    {{ category.description }}
                <div style="display: flex; gap: 8px; flex-wrap: wrap;">

                    {% for subcategory in category.subcategories.all %}
                    <div style="display: flex; align-items: center; gap: 5px;">

                        <div style="width: 10px; height: 10px; background-color: {{subcategory.color}}">

                        </div>
                        <a href="{% url 'forum:threads_by_category' subcategory.slug %}">
                            {{ subcategory.name }}
                        </a>
                    </div>
                    {% endfor %}
                </div>

                </p>
            </div>
            <div class="column is-1">
                <span class="is-size-7">
                    {{ category.get_recent_3_threads.count }}
                </span>
            </div>
            <div class="column">
                <ul>
                    {% for thread in category.get_recent_3_threads %}
                    <li>
                        <a href="{% url 'forum:thread_detail' thread.slug %}">
                            {{ thread.title }}
                        </a>
                        <small>{{ thread.created_at | naturaltime }}</small>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

apps/core/templates/core/islands/frontpage_mobile_partial.html
{% load humanize %}
<div class="box" style="background-color: transparent; border-radius: 0%;">
    {% for category in categories %}
    <div class="media">
        <div class="media-content">
            <h5 class="title is-5">
                <a href="{% url 'forum:threads_by_category' category.slug %}">
                    <span class="tag is-dark" style="background-color: {{category.color}};">
                        {{ category.name }}
                    </span>
                </a>
            </h5>
            {% for thread in category.get_recent_3_threads %}
            <a href="{% url 'forum:thread_detail' thread.id %}">
                {{ thread.title }}
            </a>
            <br>
            {% endfor %}
            {{ category.get_recent_3_threads.count }} Total
        </div>
    </div>
    {% endfor %}

apps/core/templates/core/islands/header.html
{% if title %}
<section class="hero is-{{ tag|default:'success' }} is-small">
    <div class="hero-body">
        <p class="title">
            {{ title }}
        </p>
        <p class="subtitle">
            {{ subtitle }}
        </p>
    </div>
</section>
{% endif %}

apps/core/templates/core/islands/nav.html
{% load static %}
<nav class="navbar fern-nav mx-6 my-4 p-2 {{NAVBAR_CLASS}}" style="{{NAVBAR_STYLE}}" role="navigation"
    aria-label="main navigation">
    <div class="navbar-brand">
        <a class="navbar-item" href="{% url 'core:frontpage' %}">
            <span class="icon mr-2">
                <img src="{{ LOGO_PATH }}" width="30" alt="Logo" title="Fern 🌱">
            </span>
            <span class="is-hidden-touch"><strong>{{ site_title }}</strong></span>
        </a>

        <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" _="on click toggle .is-active on .navbar-menu
            on click toggle .is-active on me
            ">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
        </a>
    </div>

    <div class="navbar-menu">
        <div class="navbar-start">

            {% for link in LINKS %}
            <a class="navbar-item" href="{{ link.url }}" hx-boost="{{ link.boost }}">
                {{ link.name }}
            </a>
            {% endfor %}

        </div>
    </div>

    <div class="navbar-end">
        <div class="navbar-item">
            <div class="buttons">
                <!-- search button -->
                <a href="{% url 'core:search' %}" class="button"><span class="icon"><i class="bi bi-search"></i></span><span>Search</span></a>
                {% if user.is_authenticated %}
                <div class="dropdown is-hoverable is-right" style="padding-right: 10px;">
                    <div class="dropdown-trigger">
                        <a class="button is-ghost" href="{% url 'account:user_detail' user.username %}"
                            aria-haspopup="true" aria-controls="dropdown-menu4">
                            <article class="image is-36x36">
                                <img src="{{ user.userprofile.avatar_image }}" alt="{{ user.username }}'s Avatar"
                                    class="{{ user.profile.status }} is-rounded" width="100" height="100">
                            </article>
                        </a>
                    </div>
                    <div class="dropdown-menu" id="dropdown-menu4" role="menu">
                        <div class="dropdown-content">
                            <div class="dropdown-item">
                                <a href="{% url 'account:user_detail' user.username %}">Your Profile</a>
                            </div>
                            <div class="dropdown-item">
                                <a href="{% url 'notification:notification_page' %}">Notifications
                                    ({{ notification_count }})</a>
                            </div>
                        </div>
                    </div>
                </div>
                <a class="button is-danger shadow" href="{% url 'account:logout' %}">
                    Log out
                </a>
                {% else %}
                <a class="button is-white special-dark" href="{% url 'account:signup' %}">
                    <strong>Sign up</strong>
                </a>
                <a class="button" href="{% url 'account:login' %}">
                    <span class="icon"><i class="bi bi-joystick"></i></span>
                    <span>
                        Log in
                    </span>
                </a>
                {% endif %}
            </div>
        </div>
    </div>
    </div>
</nav>

apps/core/templates/core/islands/pagination.html
<div {% if page.has_next %} hx-get="?q={{query}}&page={{ page.next_page_number }}" hx-replace-url="true"
    hx-trigger="revealed" hx-swap="outerHTML"
    {% endif %}>
    {% include 'islands/loader.html' %}
    <noscript>
        {% include 'core/islands/pagination_buttons.html' %}
    </noscript>
</div>

apps/core/templates/core/islands/pagination_buttons.html
{% if page.has_next or page.has_previous %}
<nav class="pagination is-centered is-small mt-2" role="navigation" aria-label="pagination">
    <ul class="pagination-list">
        {% if page.has_previous %}
        <a class="pagination-link" aria-label="Goto page 1" href="?q={{query}}&page=1">First Page</a>
        <a class="pagination-link" href="?q={{query}}&page={{ page.previous_page_number }}">«
            Previous</a>
        {% endif %}
        <a class="pagination-link is-current" aria-label="Goto page {{ page.number }}">{{ page.number }}</a>
        {% if page.has_next %}
        <a class="pagination-link" href="?q={{query}}&page={{ page.next_page_number }}">Next page
            »</a>
        <a class="pagination-link" aria-label="Goto page 4&amp;query="
            href="?q={{query}}&page={{ page.paginator.num_pages }}">Last
            Page</a>
        {% endif %}
    </ul>
</nav>
{% endif %}

apps/core/templates/core/islands/search_results.html
{% if type_filter == "threads" %}
{% for thread in results %}
<div class="box">

    {% include 'forum/islands/thread_list.html' %}
</div>
{% endfor %}
{% elif type_filter == "posts" %}
{% for post in results %}
<div class="box">
{% include 'forum/islands/post_display.html' %}
</div>
{% endfor %}
{% elif type_filter == "users" %}
{% for user in results %}
<div class="box">
    {% include 'account/islands/users_list.html' with users=results %}
</div>
{% endfor %}
{% elif type_filter == "categories" %}
{% for category in results %}
<div class="box">
    {% include 'forum/islands/category_tree.html' with categories=results %}
</div>
{% endfor %}
{% else %}
<p>No categories found.</p>

{% endif %}