Fern/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.static import serve

urlpatterns = [
    path("admin/doc/", include("django.contrib.admindocs.urls")),
    path("admin/", admin.site.urls),
    path("", include("apps.core.urls")),
    path("polls/", include("apps.polls.urls")),
    path("forum/", include("apps.forum.urls")),
    path("accounts/", include("apps.account.urls")),
    path("accounts/", include("apps.account.admin_urls")),
    path("notifications/", include("apps.notification.urls")),
    path("", include("user_sessions.urls", "user_sessions")),
    path("media/<path:path>", serve, {"document_root": settings.MEDIA_ROOT}),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/polls/urls.py
from django.urls import path
from . import views
from . import islands

app_name = "polls"
urlpatterns = [
    path("", views.index, name="index"),
    path("create/", views.poll_create, name="poll_create"),
    path('my-polls/', views.my_polls, name="my_polls"),
    path('view/<int:pk>/', views.poll_detail, name='poll_detail'),
    path('edit/<int:pk>/', views.poll_edit, name='poll_edit'),
    path('edit/<int:pk>/add-choice/', views.poll_choice_create, name='poll_choice_create'),
    path('delete-choice/<int:pk>/', views.poll_choice_delete, name='poll_choice_delete'),
    path('delete/<int:pk>/', views.poll_delete, name='poll_delete'),
    path('vote/<int:pk>/', views.vote, name='poll_vote'),


    # Islands
    path('create/choice/', islands.choice_create, name="choice_create"),
]

apps/polls/models.py
from django.db import models
from apps.forum.models import Thread
from django.utils.translation import gettext_lazy as _
from apps.account.models import User, get_sentinel_user


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published", auto_now=True)
    created_by = models.ForeignKey(
        verbose_name=_("Created By"),
        to=User,
        related_name="questions",
        on_delete=models.SET(get_sentinel_user),
    )
    voted_by = models.ManyToManyField(
        verbose_name=_("Votes"), to=User, blank=True, related_name="voted_questions"
    )

    def __str__(self):
        return self.question_text

    def has_user_voted(self, user):
        # Check if the user has voted on the question.
        return self.voted_by.filter(pk=user.pk).exists()

    class Meta:
        ordering = ["-pub_date"]


class Choice(models.Model):
    question = models.ForeignKey(
        Question, related_name="choices", on_delete=models.CASCADE
    )
    choice_text = models.CharField(max_length=200)
    votes = models.PositiveIntegerField(
        verbose_name=_("No. of Votes"),
        default=0,
    )
    voted_by = models.ManyToManyField(
        verbose_name=_("Votes"), to=User, blank=True, related_name="voted_choices"
    )

    def __str__(self):
        return self.choice_text

    def vote_percentage(self):
        total_votes = self.question.voted_by.count()
        
        if total_votes == 0:
            return '0.00'  # Return a string with two decimal places
        
        percentage = (self.votes / total_votes) * 100
        return '{:.2f}'.format(percentage)

    def vote(self, user):
        if not self.question.has_user_voted(user):
            self.votes += 1
            self.voted_by.add(user)
            self.question.voted_by.add(user)
            self.question.save()
            self.save()

apps/polls/forms.py
from django.forms import ModelForm
from .models import Question, Choice

class QuestionCreationForm(ModelForm):
    class Meta:
        model = Question
        fields = ['question_text']


class ChoiceCreationForm(ModelForm):
    class Meta:
        model = Choice
        fields = ['choice_text']

apps/polls/views.py
from django.shortcuts import render, redirect
from django.contrib import messages

from django.contrib.auth.decorators import login_required
from .forms import QuestionCreationForm, ChoiceCreationForm
from .models import Choice, Question

from apps.core.utils import is_htmx, paginate
from django.shortcuts import get_object_or_404


@login_required
def index(request):
    qform = QuestionCreationForm()
    questions = paginate(request, Question.objects.all())
    return render(request, "polls/index.html", {"questions": questions, "qform": qform})


@login_required
def poll_create(request):
    if request.method == "POST":
        qform = QuestionCreationForm(request.POST)
        if qform.is_valid():
            question = qform.save(commit=False)
            question.created_by = request.user
            question.save()
            messages.success(request, "Your question has been created!")
            return redirect("polls:poll_edit", question.id)
    qform = QuestionCreationForm()
    return render(request, "polls/poll_create.html", {"qform": qform})


@login_required
def my_polls(request):
    questions = paginate(request, Question.objects.filter(created_by=request.user))
    return render(request, "polls/my_polls.html", {"questions": questions})


@login_required
def poll_detail(request, pk):
    question = get_object_or_404(Question, pk=pk)
    is_voted = question.has_user_voted(request.user)
    return render(
        request, "polls/poll_detail.html", {"question": question, "is_voted": is_voted}
    )


@login_required
def poll_edit(request, pk):
    question = get_object_or_404(Question, pk=pk)
    if request.method == "POST":
        qform = QuestionCreationForm(request.POST, instance=question)
        if qform.is_valid():
            qform.save()
            messages.success(request, "Your question has been updated!")
            return redirect("polls:poll_edit", pk)
    qform = QuestionCreationForm(instance=question)
    return render(
        request, "polls/poll_edit.html", {"qform": qform, "question": question}
    )


@login_required
def poll_choice_create(request, pk):
    question = get_object_or_404(Question, pk=pk)
    if request.method == "POST":
        cform = ChoiceCreationForm(request.POST)
        if cform.is_valid():
            choice = cform.save(commit=False)
            choice.question = question
            choice.save()
            messages.success(request, "Your choice has been created!")
            if request.POST.get("save_and_continue"):
                return redirect("polls:poll_choice_create", pk)
            return redirect("polls:poll_edit", pk)

    cform = ChoiceCreationForm()
    return render(
        request, "polls/poll_choice_create.html", {"cform": cform, "question": question}
    )


@login_required
def poll_choice_delete(request, pk):
    choice = get_object_or_404(Choice, pk=pk, question__created_by=request.user)
    if request.method == "POST":
        choice.delete()
        messages.success(request, "Your choice has been deleted!")
    return redirect("polls:poll_edit", choice.question.id)


@login_required
def poll_delete(request, pk):
    question = get_object_or_404(Question, pk=pk, created_by=request.user)
    if request.method == "POST":
        question.delete()
        messages.success(request, "Your question has been deleted!")
    return redirect("polls:index")


@login_required
def vote(request, pk):
    question = get_object_or_404(Question, pk=pk)
    if request.method == "POST" and not question.has_user_voted(request.user):
        choice_id = request.POST.get("choice")
        choice = get_object_or_404(Choice, pk=choice_id)
        choice.votes += 1
        choice.voted_by.add(request.user)
        question.voted_by.add(request.user)
        choice.save()
        messages.success(request, "Your vote has been recorded!")
    return redirect("polls:poll_detail", pk)

apps/polls/templates/polls/index.html
{% extends 'base.html' %}
{% load humanize %}
{% load convert_markdown %}


{% block title %}
Create Poll
{% endblock title %}
{% block content %}
<div class="buttons">
    <a href="{% url 'polls:poll_create' %}" class="button is-primary">Create Poll</a>
</div>
<h1 class="title">Current Polls</h1>


{% for question in questions %}
{% include 'polls/islands/question_block.html' %}
{% endfor %}
{% include 'core/islands/pagination_buttons.html' with page=questions %}



{% endblock content %}

apps/polls/templates/polls/my_polls.html
{% extends 'base.html' %}
{% load humanize %}
{% load convert_markdown %}


{% block title %}
Create Poll
{% endblock title %}
{% block content %}
<h1 class="title is-2">My Poll</h1>
<hr>

{% for question in questions %}
{% include 'polls/islands/question_block.html' %}
{% endfor %}

{% endblock content %}

apps/polls/templates/polls/poll_choice_create.html
{% extends 'base.html' %}
{% load humanize %}
{% load convert_markdown %}


{% block title %}
Create Poll
{% endblock title %}
{% block content %}
<h1 class="title is-2">Create Choice</h1>
<p class="subtitle">
    <a href="{% url 'polls:poll_edit' question.id %}">&LeftArrow; Back</a>
</p>
<form action="." method="POST">
    {{ cform }}
    {% csrf_token %}
    <div class="field">
        <div class="control">
            <div class="buttons">
                <button type="submit" class="button is-primary">Save</button>
                <button class="button is-link" name="save_and_continue" value="true">Save and Add Another</button>
            </div>
        </div>
    </div>
</form>


{% endblock content %}

apps/polls/templates/polls/poll_create.html
{% extends 'base.html' %}
{% load humanize %}
{% load convert_markdown %}


{% block title %}
Create Poll
{% endblock title %}
{% block content %}
<h1 class="title is-2">Create Poll</h1>
<p class="subtitle">First, enter the Question Text. Then, you’ll be able to add choices.</p>
<form action="." method="POST">
    {{ qform }}
    {% csrf_token %}
    <div class="field">
        <div class="control">
            <div class="buttons">
                <button type="submit" class="button is-primary">Save</button>
            </div>
        </div>
    </div>
</form>


{% endblock content %}

apps/polls/templates/polls/poll_detail.html
{% extends 'base.html' %}
{% load humanize %}
{% load convert_markdown %}


{% block title %}
Create Poll
{% endblock title %}
{% block content %}
{% include 'polls/islands/question_block.html' %}



{% if question.choices %}
<form action="{% url 'polls:poll_vote' question.id %}" method="POST">
    {% csrf_token %}
    <div class="control box">
        {% for choice in question.choices.all %}
        {% if user not in question.voted_by.all %}
        <input type="radio" name="choice" value="{{ choice.id }}">
        {% endif %}
        {{ choice }} {% if user in question.voted_by.all %}<progress
            class="progress is-{% cycle 'primary' 'link' 'success' 'info' 'warning' 'danger' %}"
            value="{{ choice.vote_percentage }}" max="100">{{ choice.vote_percentage }} %</progress>
        {% endif %}
        </label>
        <br>
        {% endfor %}

        <div class="field mt-4">
            <div class="control">
                <button class="button is-info">Vote</button>
            </div>
        </div>
    </div>
    {% endif %}
</form>
{% endblock content %}

apps/polls/templates/polls/poll_edit.html
{% extends 'base.html' %}
{% load humanize %}
{% load convert_markdown %}


{% block title %}
Create Poll
{% endblock title %}
{% block content %}
<h1 class="title is-2">Edit Poll</h1>
<p class="subtitle">
    <a href="{% url 'polls:poll_detail' question.id %}">&LeftArrow; Back</a>
</p>
<form action="." method="POST">
    {{ qform }}
    {% csrf_token %}
    <div class="field">
        <div class="control">
            <div class="buttons">
                <button type="submit" class="button is-primary">Save</button>
                <a href="{% url 'polls:poll_choice_create' question.id %}" class="button is-link">Add Choice</a>
            </div>
        </div>
    </div>
</form>
<br>
{% if question.choices.all %}
<div class="field">
    <label class="label">Choices</label>
    <ul>
        {% for choice in question.choices.all %}
        <div class="mb-2">
            <li class="is-flex">
                - {{ choice.choice_text }} |
                <form action="{% url 'polls:poll_choice_delete' choice.id %}" method="post">
                    {% csrf_token %}
                    <button class="ml-2 is-danger is-small">Delete</button>
                </form>
            </li>
        </div>
        {% endfor %}
    </ul>
</div>
{% endif %}


{% endblock content %}