Fern/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.static import serve

urlpatterns = [
    path("admin/doc/", include("django.contrib.admindocs.urls")),
    path("admin/", admin.site.urls),
    path("", include("apps.core.urls")),
    path("polls/", include("apps.polls.urls")),
    path("forum/", include("apps.forum.urls")),
    path("accounts/", include("apps.account.urls")),
    path("accounts/", include("apps.account.admin_urls")),
    path("notifications/", include("apps.notification.urls")),
    path("", include("user_sessions.urls", "user_sessions")),
    path("media/<path:path>", serve, {"document_root": settings.MEDIA_ROOT}),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/account/urls.py
from django.urls import path, include
from . import views

app_name = "account"
urlpatterns = [
    path("", include("django.contrib.auth.urls")),
    path("register/", views.signup, name="signup"),
    path("user/<str:username>/", views.user_detail, name="user_detail"),
    path("user/<str:username>/preference/", views.user_preference, name="user_preference"),
]

apps/forum/urls.py
from django.urls import path
from . import views, islands

app_name = "forum"

urlpatterns = [
    path("create/", views.thread_create, name="thread_create"),
    path("create/<str:category_slug>/", views.thread_create, name="thread_create"),
    path("t/<slug:slug>/", views.thread_detail, name="thread_detail"),
    path("t/<slug:thread_slug>/<int:post_pk>", views.post_detail, name="post_detail"),
    # Post edit
    path("<int:pk>/edit/", views.post_edit, name="post_edit"),
    path("<int:pk>/reply/", views.reply_create, name="reply_create"),
    path("<int:pk>/delete/", views.delete_post, name="delete_post"),

    path('c/<str:slug>/', views.threads_by_category, name='threads_by_category'),
    path('c/', views.categories_list, name='categories_list'),

    # Islands
    path("islands/reply/<int:pk>/", islands.reply_form, name="reply_form"),
    path("islands/like/<int:pk>/", islands.like_post, name="like_post"),
    path('islands/threads/<int:pk>/', islands.thread_post_list, name='thread_post_list'),
    path('islands/threads/<int:pk>/reply-button/', islands.reply_button, name='reply_button'),
    path('islands/threads/<int:pk>/post-block/', islands.post_block, name='post_block'),
    path('islands/category-filter/', islands.category_filter, name='category_filter'),

    # Upload
    path("upload/", views.upload_file, name="upload_file"),  # New upload path
    path('islands/upload-modal/', islands.upload_modal, name='upload_modal'),
    path('islands/upload-form/', islands.upload_form, name='upload_form'),
    path('islands/existing-uploads/', islands.existing_uploads, name='existing_uploads_island'),
    path('islands/close-modal/', islands.close_modal, name='close_modal'),
    path('islands/insert-upload/<int:pk>/', islands.insert_upload, name='insert_upload'),

    path("uploads/", views.existing_uploads, name="existing_uploads"),  # New existing uploads path
    path("uploads/<int:pk>/delete/", views.delete_upload, name="delete_upload"),

    path('link/<int:pk>/click/', views.link_click, name='link_click')


]

templates/user_sessions/_base.html
{% extends 'base.html' %}
{% block content_wrapper %}
    <div class="container">
      {% block content %}{% endblock %}
    </div>
  {% endblock %}

templates/user_sessions/session_list.html
{% extends "user_sessions/_base.html" %}
{% load user_sessions i18n %}
{% load convert_markdown %}


{% block title %}
Your Sessions
{% endblock title %}
{% block content %}
{% include 'account/islands/user_summary_block.html' with tuser=user %}
<div class="block mt-3" style="border-top: 1px solid rgb(58, 58, 58); 
    border-bottom: 1px solid rgb(58, 58, 58); 
    padding-top: 10px; 
    padding-bottom: 10px;">
  <span>
    <span class="has-text-weight-bold">
      Joined:
    </span>
    {{ tuser.date_joined }}</span>
</div>
<div class="tabs is-centered is-fullwidth">
  <ul>
    <li><a href="{% url 'account:user_detail' user.username %}"><span class="icon"><i class="bi bi-person-fill"></i></span><span></span>Summary</span></a></li>
    <li class="is-active"><a href="{% url 'user_sessions:session_list' %}"><span class="icon"><i class="bi bi-broadcast-pin"></i></span><span>Activity</span></a></li>
        <li><a href="{% url 'forum:existing_uploads' %}"><span class="icon"><i class="bi bi-archive-fill"></i></span><span>Your Uploads</span></a></li>

    <li><a href="{% url 'account:user_preference' user.username %}"><span class="icon"><i class="bi bi-gear-wide-connected"></i></span><span>Preferences</span></a></li>
  </ul>
</div>

{% trans "<em>unknown on unknown</em>" as unknown_on_unknown %}
{% trans "<em>unknown</em>" as unknown %}

<h1 class="title">{% trans "Active Sessions" %}</h1>
<div class="table-container">
  <table class="table is-fullwidth is-bordered">
    <thead>
      <tr>
        <th>{% trans "Location" %}</th>
        <th>{% trans "Device" %}</th>
        <th>{% trans "Last Activity" %}</th>
      </tr>
    </thead>
    {% for object in object_list %}
    <tr {% if object.session_key == session_key %}class="is-selected" {% endif %}>
      <td>{{ object.ip|location|default_if_none:unknown|safe }} <small>({{ object.ip }})</small></td>
      <td>{{ object.user_agent|device|default_if_none:unknown_on_unknown|safe }}</td>
      <td>
        {% if object.session_key == session_key %}
        {% blocktrans with time=object.last_activity|timesince %}{{ time }} ago (this session){% endblocktrans %}
        {% else %}
        {% blocktrans with time=object.last_activity|timesince %}{{ time }} ago{% endblocktrans %}
        {% endif %}
      </td>
    </tr>
    {% endfor %}
  </table>
</div>

{% if object_list.count > 1 %}
<form method="post" action="{% url 'user_sessions:session_delete_other' %}">
  {% csrf_token %}
  <p>{% blocktrans %}You can also end all other sessions but the current.
    This will log you out on all other devices.{% endblocktrans %}</p>
  <br>
  <div class="field">
    <div class="control">
      <button type="submit" class="button is-warning is-responsive is-outlined">{% trans "End All Other Sessions" %}</button>
    </div>
  </div>
</form>
{% endif %}
{% endblock %}