Fern/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.static import serve

urlpatterns = [
    path("admin/doc/", include("django.contrib.admindocs.urls")),
    path("admin/", admin.site.urls),
    path("", include("apps.core.urls")),
    path("polls/", include("apps.polls.urls")),
    path("forum/", include("apps.forum.urls")),
    path("accounts/", include("apps.account.urls")),
    path("accounts/", include("apps.account.admin_urls")),
    path("notifications/", include("apps.notification.urls")),
    path("", include("user_sessions.urls", "user_sessions")),
    path("media/<path:path>", serve, {"document_root": settings.MEDIA_ROOT}),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/core/urls.py
from django.urls import path
from . import views

app_name = "core"
urlpatterns = [
    path("", views.FrontpageView.as_view(), name="frontpage"),
    path("home/", views.HomeView.as_view(), name="homepage"),
    path(
        "convert/md/", views.convert_markdown_to_html, name="convert_markdown_to_html"
    ),
    path("search/", views.search, name="search"),
]

apps/forum/urls.py
from django.urls import path
from . import views, islands

app_name = "forum"

urlpatterns = [
    path("create/", views.thread_create, name="thread_create"),
    path("create/<str:category_slug>/", views.thread_create, name="thread_create"),
    path("t/<slug:slug>/", views.thread_detail, name="thread_detail"),
    path("t/<slug:thread_slug>/<int:post_pk>", views.post_detail, name="post_detail"),
    # Post edit
    path("<int:pk>/edit/", views.post_edit, name="post_edit"),
    path("<int:pk>/reply/", views.reply_create, name="reply_create"),
    path("<int:pk>/delete/", views.delete_post, name="delete_post"),

    path('c/<str:slug>/', views.threads_by_category, name='threads_by_category'),
    path('c/', views.categories_list, name='categories_list'),

    # Islands
    path("islands/reply/<int:pk>/", islands.reply_form, name="reply_form"),
    path("islands/like/<int:pk>/", islands.like_post, name="like_post"),
    path('islands/threads/<int:pk>/', islands.thread_post_list, name='thread_post_list'),
    path('islands/threads/<int:pk>/reply-button/', islands.reply_button, name='reply_button'),
    path('islands/threads/<int:pk>/post-block/', islands.post_block, name='post_block'),
    path('islands/category-filter/', islands.category_filter, name='category_filter'),

    # Upload
    path("upload/", views.upload_file, name="upload_file"),  # New upload path
    path('islands/upload-modal/', islands.upload_modal, name='upload_modal'),
    path('islands/upload-form/', islands.upload_form, name='upload_form'),
    path('islands/existing-uploads/', islands.existing_uploads, name='existing_uploads_island'),
    path('islands/close-modal/', islands.close_modal, name='close_modal'),
    path('islands/insert-upload/<int:pk>/', islands.insert_upload, name='insert_upload'),

    path("uploads/", views.existing_uploads, name="existing_uploads"),  # New existing uploads path
    path("uploads/<int:pk>/delete/", views.delete_upload, name="delete_upload"),

    path('link/<int:pk>/click/', views.link_click, name='link_click')


]

apps/core/models.py
from django.db import models
# Define you models here.

apps/core/views.py
from django.shortcuts import HttpResponse, render
from django.views import View
from django.views.generic import TemplateView
from django.db.models import Q

from apps.account.templatetags.user_mention import user_mention
from apps.forum.models import Category, Thread, Post
from apps.account.models import User

from .templatetags.convert_markdown import convert_markdown
from .utils import paginate, is_htmx


class FrontpageView(View):
    template_name = "core/frontpage.html"

    def get(self, request):
        categories = Category.objects.filter(parent__isnull=True).prefetch_related(
            "subcategories", "threads"
        )
        context = {"categories": categories}
        return render(request, self.template_name, context)


def convert_markdown_to_html(request):
    input_param = request.POST.get("name", default="text")
    text = request.POST.get(input_param)
    html = user_mention(convert_markdown(text))
    return HttpResponse(html)


class HomeView(TemplateView):
    template_name = "core/home.html"


def search(request):
    query = request.GET.get("q", "")
    type_filter = request.GET.get("type", "threads")
    results = []
    if query and type_filter:
        if type_filter == "threads":
            results = (
                Thread.objects.filter(
                    Q(title__icontains=query)
                    | Q(created_at__icontains=query)
                    | Q(creator__username__icontains=query)
                )
                .select_related("category")
                .prefetch_related("posts")
                .order_by("-created_at")
            )
        elif type_filter == "posts":
            results = (
                Post.objects.filter(
                    Q(thread__title__icontains=query) | Q(body__icontains=query)
                )
                .select_related("thread", "thread__category")
                .order_by("-created_at")
            )
        elif type_filter == "users":
            results = (
                User.objects.filter(username__icontains=query)
                .select_related("userprofile")
                .prefetch_related("posts")
                .order_by("-date_joined")
            )
        elif type_filter == "categories":
            results = (
                Category.objects.filter(name__icontains=query)
                .prefetch_related("threads")
                .order_by("name")
            )
    results = paginate(request, results, 10)
    context = {"query": query, "type_filter": type_filter, "results": results}
    if is_htmx(request):
        return render(request, "core/islands/search_results.html", context)
    else:
        return render(request, "core/search.html", context)

apps/core/templates/core/frontpage.html
{% extends 'base.html' %}
{% block title %} Home {% endblock title %}

{% block content %}
<div class="content mx-6">
    <a href="{% url 'forum:thread_create' %}" class="button">Create Thread</a>
</div>
<div class="is-hidden-mobile">
    {% include 'core/islands/frontpage_desktop_partial.html' %}
</div>
<div class="is-hidden-tablet">
    {% include 'core/islands/frontpage_mobile_partial.html' %}
</div>


{% endblock content %}

apps/core/templates/core/home.html
{% extends 'base.html' %}
{% block title %} Home {% endblock title %}

{% block content %}
<div class="has-text-centered">
    <h1 class="title is-1 has-text-weight-black">Fern</h1>
</div>

{% endblock content %}

apps/core/templates/core/search.html
{% extends 'base.html' %}
{% load humanize %}
{% load convert_markdown %}

{% block title %}
Search
{% endblock title %}

{% block content %}
<div class="box">
    <h1 class="title">

        {% if query %}
        {{ results|length }} results for "<strong>{{ query }}</strong>"
        {% else %}
        Seach
        {% endif %}
        <p class="subtitle">Search across the site</p>
        <form action=".">
            <div class="columns is-multiline">
                <div class="column is-10">
                    <input type="text" name="q" class="input" placeholder="Search..." value="{{ query }}">
                </div>
                <div class="column is-2">
                    <div class="field">
                        <div class="control">
                            <div class="select">
                                <select name="type" class="input" name="type">
                                    <option value="threads" {% if type_filter == "threads" %}selected{% endif %}>Threads
                                    </option>
                                    <option value="posts" {% if type_filter == "posts" %}selected{% endif %}>Posts
                                    </option>
                                    <option value="users" {% if type_filter == "users" %}selected{% endif %}>Users
                                    </option>
                                    <option value="categories" {% if type_filter == "categories" %}selected{% endif %}>
                                        Categories</option>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="field">
                <div class="control">
                    <button type="submit" class="button is-medium">Search</button>
                </div>
            </div>
        </form>

    </h1>
</div>

<br>
<br>
{% include 'core/islands/search_results.html' %}

{% endblock content %}